### ISSUE TITLE
Dying Light Fix

### ISSUE THREAD

**Issue by XenonPK** [steamtricks/steamtricks-data#6]
It seems @GloriousEggroll ([and reddit](https://www.reddit.com/r/linux_gaming/comments/9jd2y0/how_to_play_dying_light_in_arch_linux/)) have found a fix for [dying light with mesa](https://www.youtube.com/watch?v=dYwpKQDBQm0)... 

It seems it requires us to compile a separate version of mesa with glvnd disabled, and make this available through LD_PRELOAD or equivalent.

Would it be feasible to leverage obs to make this a seamless process?

**Comment by GloriousEggroll** [comment]
this is not a universal solution because mesa has to be compiled with whatever version of LLVM is on the system its running on, which would also change on every mesa and llvm update

**Comment by XenonPK** [comment]
That's why I think obs could be leveraged for this, we can have a version of mesa built in tandem with the main mesa package, for steamtricks to use.

It would be integrated with the distro and update alongside the system's Mesa & LLVM. I believe something similar has been done before for openssl.
